### ISSUE TITLE
Idempotent command handling enhancements

### ISSUE THREAD

**Issue by aedwardstx** [netdevops/hier_config#61]
- [ ] Find a way to use a single idempotency rule for the following:
```
client 10.1.1.1 server-key
client 10.2.2.2 server-key 
```
```
#e.g.
idempotent_commands:
- lineage:
  - re_search: ^client {client_ip} server-key 
```
- [ ] See what we can do to clarify this or improve HConfig behavior
For the best results, idempotent command lineage rules should be a single match per rule e.g.
```
idempotent_commands:
- lineage:
  - startswith: hardware access-list tcam region
- lineage:
  - startswith: hardware profile tcam region
```
If you were to lump them together, an idempotent command check for `hardware profile tcam region X` would be True if `hardware access-list tcam region Y` were in the compiled_config.  Much of the time, this is still okay but there are cases where it is not. In certain cases, this behavior can shadow command negations.
- [ ] Restructure Idempotent rules to not require the word `lineage` over and over
```
idempotent_commands:
- - startswith: aaa authentication attempts
- - startswith: aaa authentication login
- - startswith: aaa authentication enable
- - startswith: interface # Support for deep rules
  - startswith: description
```
