### ISSUE TITLE
ordering doesn't appear to work

### ISSUE THREAD

**Issue by grahamn-gr** [netdevops/hier_config#90]
I'm trying to ensure that an ACL gets created before any other commands. It seems that by lowering the order ensures that it will get created before everything else which has a value of 500. (As a test I've also changed it so it's a greater number than 500 and still makes no difference)

I've set the below in my options.yml file but it doesn't take affect, the output file always shows that the ACL is going to be applied in the same place.

```
ordering:
- lineage:
  - startswith:
    - ip access-list
  order: 1
```
